image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - rm -rf .terraform
  - terraform init

stages:
  - validate
  - plan

validate:
  stage: validate
  script:
    - terraform validate
    - terraform fmt -check
  except:
    - main

plan:
  stage: plan
  script:
    - terraform plan -detailed-exitcode
  only:
    - merge_requests
